export const ADD_TO_COMMODITY = "ADD_TO_COMMODITY";
export const DELETE_FROM_COMMODITY = "DELETE_FROM_COMMODITY";
export const ADD_TO_SERVICES = "ADD_TO_SERVICES";
export const DELETE_FROM_SERVICES = "DELETE_FROM_SERVICES";
export const ADD_TO_MASSIVE_OF_ESTIMATES = "ADD_TO_MASSIVE_OF_ESTIMATES";
export const DELETE_FROM_MASSIVE_OF_ESTIMATES = "DELETE_FROM_MASSIVE_OF_ESTIMATES";